networks:
  ecom-network:
    external: true

volumes:
  userdb_data:
  productdb_data:
  orderdb_data:
  rabbitmq_data:
  zookeeper_data:
  kafka_data:

services:
  user-db:
    image: mongo:6.0
    container_name: ecom-user-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: userdb
    ports:
      - "27017:27017"
    volumes:
      - userdb_data:/data/db
    networks:
      - ecom-network

  product-db:
    image: postgres:14.18
    container_name: ecom-product-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    ports:
      - "5434:5432"
    volumes:
      - productdb_data:/var/lib/postgresql/data
    networks:
      - ecom-network

  order-db:
    image: postgres:14.18
    container_name: ecom-order-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orderdb
    ports:
      - "5435:5432"
    volumes:
      - orderdb_data:/var/lib/postgresql/data
    networks:
      - ecom-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ecom-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ecom-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: ecom-zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
    networks:
      - ecom-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: ecom-kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - ecom-network
