networks:
  ecom-network:
    external: true

volumes:
  grafana-data:
  minio-data:

services:
  read:
    image: grafana/loki:3.1.1
    platform: linux/arm64
    command: -config.file=/etc/loki/config.yaml -target=read
    ports:
      - 3101:3100
    volumes:
      - ../loki/loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecom-network

  write:
    image: grafana/loki:3.1.1
    platform: linux/arm64
    command: -config.file=/etc/loki/config.yaml -target=write
    ports:
      - 3102:3100
    volumes:
      - ../loki/loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecom-network

  alloy:
    image: grafana/alloy:latest
    platform: linux/arm64
    volumes:
      - ../alloy/alloy-local-config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ../../logs:/logs:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - 12345:12345
    depends_on:
      - gateway
    networks:
      - ecom-network

  minio:
    image: quay.io/minio/minio:latest
    platform: linux/arm64
    command: server /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - 9000:9000
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 15s
      timeout: 20s
      retries: 5
    networks:
      - ecom-network

  grafana:
    image: grafana/grafana:latest
    platform: linux/arm64
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - gateway
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ../grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecom-network

  backend:
    image: grafana/loki:3.1.1
    platform: linux/arm64
    volumes:
      - ../loki/loki-config.yaml:/etc/loki/config.yaml
    ports:
      - 3103:3100
    command: -config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false
    depends_on:
      - gateway
    networks:
      - ecom-network

  gateway:
    image: nginx:alpine
    platform: linux/arm64
    depends_on:
      - read
      - write
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 3100:3100
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ecom-network

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - alloy
      - gateway
    networks:
      - ecom-network

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - ecom-network



