global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'user-service-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'user-service'

  - job_name: 'product-service-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'product-service'

  - job_name: 'order-service-local'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'order-service'

  - job_name: 'user-service-docker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']
        labels:
          application: 'user-service'

  - job_name: 'product-service-docker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service:8082']
        labels:
          application: 'product-service'

  - job_name: 'order-service-docker'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service:8083']
        labels:
          application: 'order-service'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

