# Name of the Spring Boot application (helps with logging, tracing, and identification in microservices)
spring.application.name=config-server

# Profile to activate ? 'native' means the config server will read from the local file system or classpath
spring.profiles.active=native

# Directory or path where the Config Server will look for configuration files when using the native profile
spring.cloud.config.server.native.search-locations=file:///Users/SUSHANKM/Learning/Java/eCommerce-microservices/config-server/src/main/resources/config

server.port=8888